### ISSUE TITLE
arakoon checksum error

### ISSUE THREAD

**Issue by hoannv46** [openvstorage/arakoon#196] opened 2017-08-14 07:35 UTC
Hi all.
I installed openvstorage in 2 dc, all server shutdown.
I start server, i cannot start ovs-arakoon-voldrv server.
This is log i run ovs-arakoon-voldrv manually, i run on 3 master node.

> 2017-08-14 14:33:47 351025 +0700 - ovs-r1-controller - 22729/0000 - arakoon - 29 - info - Not copying /mnt/hdd2/arakoon/voldrv/tlogs/head.db to /mnt/hdd2/arakoon/voldrv/db/MgilN7oBbksHsEkE.db because target already exists
2017-08-14 14:33:47 351049 +0700 - ovs-r1-controller - 22729/0000 - arakoon - 30 - info - _init ~check_marker:true ~check_sabotage:true
2017-08-14 14:33:47 351373 +0700 - ovs-r1-controller - 22729/0000 - arakoon - 31 - info - tlog_number:37
2017-08-14 14:33:47 356056 +0700 - ovs-r1-controller - 22729/0000 - arakoon - 32 - fatal - AUTOFIX: can't autofix this: Tlogcommon.TLogCheckSumError(_); backtrace:; Raised at file "map.ml", line 122, characters 16-25; Called from file "src/core/lwt.ml", line 161, characters 4-40
2017-08-14 14:33:47 356105 +0700 - ovs-r1-controller - 22729/0000 - arakoon - 33 - fatal - [rc=49] Tlog has a checksum error, last valid pos = 130497

> a53.db (overwrite=false,throttling=0.000000) buffer_size:1048576
2017-08-14 14:27:44 629300 +0700 - ovs-r2-controller - 23779/0000 - arakoon - 29 - info - Not copying /mnt/hdd1/arakoon/voldrv/tlogs/head.db to /mnt/hdd1/arakoon/voldrv/db/0vsJSdtnXhwwaa53.db because target already exists
2017-08-14 14:27:44 629338 +0700 - ovs-r2-controller - 23779/0000 - arakoon - 30 - info - _init ~check_marker:true ~check_sabotage:true
2017-08-14 14:27:44 629727 +0700 - ovs-r2-controller - 23779/0000 - arakoon - 31 - info - tlog_number:37
2017-08-14 14:27:44 634753 +0700 - ovs-r2-controller - 23779/0000 - arakoon - 32 - fatal - AUTOFIX: can't autofix this: Tlogcommon.TLogCheckSumError(_); backtrace:; Raised at file "map.ml", line 122, characters 16-25; Called from file "src/core/lwt.ml", line 161, characters 4-40
2017-08-14 14:27:44 634813 +0700 - ovs-r2-controller - 23779/0000 - arakoon - 33 - fatal - [rc=49] Tlog has a checksum error, last valid pos = 130906
root@ovs-r2-controller:/opt/OpenvStorage# /usr/bin/arakoon --node 0vsJSdtnXhwwaa53  -config arakoon://config/ovs/arakoon/voldrv/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini -autofix -start

> 2017-08-14 14:29:05 623044 +0700 - ovs-r1-performance-1 - 5698/0000 - arakoon - 28 - info - copy_file /mnt/hdd1/arakoon/voldrv/tlogs/head.db /mnt/hdd1/arakoon/voldrv/db/oKRzbz2bGb3OaGQr.db (overwrite=false,throttling=0.000000) buffer_size:1048576
2017-08-14 14:29:05 623097 +0700 - ovs-r1-performance-1 - 5698/0000 - arakoon - 29 - info - Not copying /mnt/hdd1/arakoon/voldrv/tlogs/head.db to /mnt/hdd1/arakoon/voldrv/db/oKRzbz2bGb3OaGQr.db because target already exists
2017-08-14 14:29:05 623128 +0700 - ovs-r1-performance-1 - 5698/0000 - arakoon - 30 - info - _init ~check_marker:true ~check_sabotage:true
2017-08-14 14:29:05 623512 +0700 - ovs-r1-performance-1 - 5698/0000 - arakoon - 31 - info - tlog_number:37
2017-08-14 14:29:05 628377 +0700 - ovs-r1-performance-1 - 5698/0000 - arakoon - 32 - fatal - AUTOFIX: can't autofix this: Tlogcommon.TLogCheckSumError(_); backtrace:; Raised at file "map.ml", line 122, characters 16-25; Called from file "src/core/lwt.ml", line 161, characters 4-40
2017-08-14 14:29:05 628414 +0700 - ovs-r1-performance-1 - 5698/0000 - arakoon - 33 - fatal - [rc=49] Tlog has a checksum error, last valid pos = 133881

How can i fix it. Thanks

**Comment by toolslive** [comment] 2017-08-14 11:30
It seems you have a corrupt tlog on both of your arakoon nodes. Can it be the underlying storage medium for the tlogs is unstable? 

fwiw, you can truncate a tlog using `arakoon  --truncate-tlog <filename>` but I cannot guarantee it will help in this case: we need to know the counters of the stores, and a list of existing tlogs, as well as the arakoon config. Also, there might be other corruptions as well.

**Comment by hoannv46** [comment] 2017-08-15 02:10
I have 3 master node. 
I tried copy-db-to-head but it not working. Truncate log not working.
> arakoon --copy-db-to-head config 192.168.54.23 26400 130906.
 @toolslive 

Because power loss, 3 head.db file in master not same
> root@ovs-r1-controller:/opt/OpenvStorage# ls -la /mnt/hdd2/arakoon/voldrv/tlogs/head.db 
-rw-r--r-- 1 ovs ovs 587776 Aug 12 23:10 /mnt/hdd2/arakoon/voldrv/tlogs/head.db

> root@ovs-r2-controller:/opt/OpenvStorage# ls -la /mnt/hdd1/arakoon/voldrv/tlogs/head.db 
> -rw-r--r-- 1 ovs ovs 587776 Aug 12 23:10 /mnt/hdd1/arakoon/voldrv/tlogs/head.db

> root@ovs-r1-performance-1:/opt/OpenvStorage# ls -la /mnt/hdd1/arakoon/voldrv/tlogs/head.db
> -rw-r--r-- 1 ovs ovs 603648 Aug 12 23:10 /mnt/hdd1/arakoon/voldrv/tlogs/head.db

**Comment by toolslive** [comment] 2017-08-16 08:55
the heads can be different; even the stores could be different. They have a counter to state how recent they are:
``` 
$>arakoon --dump-store <path-to-.db>
i: Some ("168761")
master: Some(abm_0,1502873370.609920)
routing : --
interval: {(_,_),(_,_)}
cluster_id: Some ("abm")
```
I'm still not clear on the condition of your cluster: is there a node that starts or not?
what are the `i` values of your stores & heads ?

If you have a node that starts, you can try to move the tlogs head and store aside on the other nodes
and start these as well, they should be able to catch up.

**Comment by hoannv46** [comment] 2017-08-16 09:06
@toolslive 

all node start after shutdown (because power loss)
I tried move tlogs head and store from other nodes but it cannot start.

**Comment by toolslive** [comment] 2017-08-16 09:18
node = arakoon process . Is there a machine where the arakoon process of the cluster keeps running after starting it ?

**Comment by hoannv46** [comment] 2017-08-16 09:22
@toolslive 
Machine where the arakoon process of the cluster keep running but arakkoon procecss activating (no active)

**Comment by wimpers** [comment] 2017-08-18 14:13
Hi @hoanhdo 

I discussed this issue with engineering and we don't believe this is caused by a bug hence I'm closing this issue down.  That doesn't of course doesn't solve your problem hence can you please open an issue in the Google Forum https://groups.google.com/forum/#!forum/open-vstorage so the operations team can help you. Please add whether there is a node that starts or not and
what the i values are of your stores & heads .

**Closed as completed by wimpers** 2017-08-18 14:13 UTC
Labels: process_wontfix
